# Dockerfile.fastapi
FROM python:3.11

WORKDIR /app

# Copy only the necessary backend files
COPY ./main.py /app/
COPY ./WebScraper.py /app/
COPY ./requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
