# Dockerfile.streamlit
FROM python:3.11

WORKDIR /app

# Copy only the necessary frontend files
COPY ./streamlit_app.py /app/
COPY ./requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Streamlit runs on
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501"]
